


#h2 database cred
spring:
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: 
  password:
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
#enabling the H2 console
 h2:
  console:
   enabled: true
